name: Run performance tests
on:
  push:
    # branches:
    #   - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.9"]

    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    environment: azure

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3

    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}

    - name: Install the project
      run: uv build

    - name: Upload the package
      uses: actions/upload-artifact@v4
      with:
        name: cshelve-${{ github.sha }}
        path: dist/*.whl
        retention-days: 10
        if-no-files-found: error
        overwrite: false

  performance-tests:
    needs: build

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
      max-parallel: 1

    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    environment: azure

    steps:
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download the package.
      uses: actions/download-artifact@v4
      with:
        name: cshelve-${{ github.sha }}
        path: performances/dist

    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Run performances tests
      working-directory: performances
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install ./dist/*.whl
        python3 main.py production.results.ini
