# Following tests are using Cloud services to ensure the quality of the project.

name: End to end tests
on: [pull_request]

permissions:
  id-token: write
  contents: read

jobs:
  infrastructure:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment: azure
    outputs:
      storage_account_name: ${{ steps.terraform-outputs.outputs.STORAGE_ACCOUNT_NAME }}
      resource_group_name: ${{ steps.terraform-outputs.outputs.RESOURCE_GROUP_NAME }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Terraform Init
      id: init
      run: terraform init
      working-directory: .devcontainer/infra/backbone

    - name: Terraform Apply
      id: apply
      run: terraform apply -auto-approve
      working-directory: .devcontainer/infra/backbone
      env:
        TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        TF_VAR_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
        TF_VAR_client_id: ${{ secrets.AZURE_CLIENT_ID }}
        TF_VAR_run_id: ${{ github.run_id }}

    - name: Cache Terraform State
      uses: actions/cache/save@v3
      with:
        path: .devcontainer/infra/backbone/terraform.tfstate
        key: terraform-state-${{ github.run_id }}

    - name: Get Storage Account Name
      id: get-storage-account
      run: terraform output -no-color storage_account_name
      working-directory: .devcontainer/infra/backbone

    - name: Get Resource Group Name
      id: get-resource-group
      run: terraform output -no-color resource_group_name
      working-directory: .devcontainer/infra/backbone

    - name: Set Outputs
      id: terraform-outputs
      run: |
        echo "STORAGE_ACCOUNT_NAME=${{ steps.get-storage-account.outputs.stdout }}" >> $GITHUB_OUTPUT
        echo "RESOURCE_GROUP_NAME=${{ steps.get-resource-group.outputs.stdout }}" >> $GITHUB_OUTPUT

    - name: Update Azure Storage Environment
      run: |
        echo "Created SFTP Storage Account: ${{ steps.terraform-outputs.outputs.STORAGE_ACCOUNT_NAME }}"
        echo "Resource Group: ${{ steps.terraform-outputs.outputs.RESOURCE_GROUP_NAME }}"

  tests:
    needs: infrastructure
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]

    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    environment: azure

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Echo Storage Account Info
      run: |
        echo "Using SFTP Storage Account: ${{ needs.infrastructure.outputs.storage_account_name }}"
        echo "Using SFTP Container: ${{ needs.infrastructure.outputs.container_name }}"

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Terraform Init (Job Container)
      id: init-job
      run: terraform init
      working-directory: .devcontainer/infra/jobs

    - name: Create Job Container
      id: job-container
      run: terraform apply -auto-approve
      working-directory: .devcontainer/infra/jobs
      env:
        TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        TF_VAR_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
        TF_VAR_client_id: ${{ secrets.AZURE_CLIENT_ID }}
        TF_VAR_run_id: ${{ github.run_id }}
        TF_VAR_os: ${{ matrix.os }}
        TF_VAR_python_version: ${{ matrix.python-version }}
        TF_VAR_storage_account_name: ${{ needs.infrastructure.outputs.storage_account_name }}
        TF_VAR_resource_group_name: ${{ needs.infrastructure.outputs.resource_group_name }}

    - name: Get Job Container Info
      id: get-job-container
      run: |
        STORAGE_ACCOUNT_NAME=$(terraform output -raw storage_account_name)
        SFTP_NAME=$(terraform output -raw sftp_name)
        CONNECTION_STRING=$(terraform output -raw storage_account_primary_connection_string)

        echo "STORAGE_ACCOUNT_NAME=${STORAGE_ACCOUNT_NAME}" >> $GITHUB_OUTPUT
        echo "SFTP_NAME=${SFTP_NAME}" >> $GITHUB_OUTPUT
        # Store connection string securely as an environment variable
        # echo "CONNECTION_STRING=${CONNECTION_STRING}" >> $GITHUB_OUTPUT
      working-directory: .devcontainer/infra/jobs

    - name: Echo Job Container Info
      run: |
        echo "Job-specific Storage Account: ${{ steps.get-job-container.outputs.STORAGE_ACCOUNT_NAME }}"
        echo "Job-specific Container: ${{ steps.get-job-container.outputs.SFTP_NAME }}"

    # Nodejs is used to install Azurite.
    - uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install uv
      uses: astral-sh/setup-uv@v3

    - name: Install Azureit to emulate Azure Storage Account locally and moto to emulate AWS S3.
      run: |
        pip install moto[server]
        npm install -g azurite

    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}

    - name: Install the project
      run: uv sync --all-extras --dev --python ${{ matrix.python-version }}

    - name: Run tests without dependencies
      run: uv run pytest tests/units

    - name: Retrieve SSH key for SFTP tests
      run: |
        echo ${{ secrets.SFTP_SSH_KEY_ECDSA }} | base64 --decode > /tmp/sftp_key_ecdsa_key
        echo ${{ secrets.SFTP_SSH_KEY_RSA }} | base64 --decode > /tmp/sftp_key_rsa_key
      shell: bash

    - name: Run end-to-end tests interracting with Azure, AWS and SFTP
      run: uv run --python ${{ matrix.python-version }} pytest -m "azure or aws or sftp" tests/end-to-end
      env:
        AWS_KEY_ID: ${{ secrets.AWS_ENVIRONMENT_KEY }}
        AWS_KEY_SECRET: ${{ secrets.AWS_ENVIRONMENT_SECRET }}
        AZURE_STORAGE_ACCESS_KEY: ${{ secrets.AZURE_STORAGE_ACCESS_KEY }}
        AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
        ENCRYPTION_KEY: "Sixteen byte key"
        SFTP_PASSWORD_HOSTNAME: ${{ secrets.SFTP_HOSTNAME }}
        SFTP_SSH_HOSTNAME: ${{ secrets.SFTP_HOSTNAME }}
        SFTP_USERNAME: ${{ secrets.SFTP_USERNAME }}
        SFTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
        SFTP_SSH_KEY_ECDSA: /tmp/sftp_key_ecdsa_key
        SFTP_SSH_KEY_RSA: /tmp/sftp_key_rsa_key
      shell: bash

    - name: Run end-to-end tests with simulator
      run: |
        # Start dependencies
        azurite --silent --location c:\azurite --debug c:\azurite\debug.log &
        moto_server -p9000 &

        # Run tests
        uv run --python ${{ matrix.python-version }} pytest -m "(not azure) and (not aws) and (not sftp)" tests/end-to-end
      env:
        AWS_ENDPOINT_URL: "http://127.0.0.1:9000"
        AWS_KEY_ID: "moto"
        AWS_KEY_SECRET: "moto"
        AZURE_STORAGE_CONNECTION_STRING: "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;"
        ENCRYPTION_KEY: "Sixteen byte key"
        SFTP_PASSWORD_HOSTNAME: ${{ secrets.SFTP_HOSTNAME }}
        SFTP_USERNAME: ${{ secrets.SFTP_USERNAME }}
        SFTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
        SFTP_SSH_KEY_ECDSA: /tmp/sftp_key_ecdsa_key
        SFTP_SSH_KEY_RSA: /tmp/sftp_key_rsa_key

  cleanup:
    needs: [tests, infrastructure]
    if: always()
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment: azure

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Restore Terraform State
      uses: actions/cache/restore@v3
      with:
        path: .devcontainer/infra/backbone/terraform.tfstate
        key: terraform-state-${{ github.run_id }}
        fail-on-cache-miss: true

    - name: Terraform Init
      id: init-cleanup
      run: terraform init
      working-directory: .devcontainer/infra/backbone

    - name: Terraform Destroy
      id: destroy
      run: terraform destroy -auto-approve -no-color
      working-directory: .devcontainer/infra/backbone
      env:
        TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        TF_VAR_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
        TF_VAR_client_id: ${{ secrets.AZURE_CLIENT_ID }}
        TF_VAR_run_id: ${{ github.run_id }}

    - name: Confirm Resource Cleanup
      run: |
        echo "Destroyed Storage Account: ${{ needs.infrastructure.outputs.storage_account_name }}"

    - name: Delete Terraform State Cache
      run: |
        echo "Cleaning up Terraform state cache..."
        rm -f .devcontainer/infra/backbone/terraform.tfstate*
      shell: bash
